### ISSUE TITLE
Error running app

### ISSUE THREAD

**Issue by ChrisB007** [BuilderIO/nextjs-shopify#35]
Hello, I followed the README carefully, but when I tried running the app I got this error below:

```
npm run dev                                                                                                  1 ↵ blkboxng@Chris

> nextjs-commerce@1.0.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /Users/blkboxng/Desktop/publicTrs/snaphubs/.env.development
info  - Using webpack 4. Reason: future.webpack5 option not enabled https://nextjs.org/docs/messages/webpack5
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/parser' is not defined by "exports" in /Users/blkboxng/Desktop/publicTradesProperties/snaphubs/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:388:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:719:3)
    at resolveExports (node:internal/modules/cjs/loader:488:36)
    at Module._findPath (node:internal/modules/cjs/loader:528:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:932:27)
    at mod._resolveFilename (/Users/blkboxng/Desktop/publicTradesProperties/snaphubs/node_modules/next/dist/build/webpack/require-hook.js:4:1784)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at 552 (/Users/blkboxng/Desktop/publicTradesProperties/snaphubs/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11590)
    at __nccwpck_require__ (/Users/blkboxng/Desktop/publicTradesProperties/snaphubs/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
    at 270 (/Users/blkboxng/Desktop/publicTradesProperties/snaphubs/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:400)
    at __nccwpck_require__ (/Users/blkboxng/Desktop/publicTradesProperties/snaphubs/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
    at 327 (/Users/blkboxng/Desktop/publicTradesProperties/snaphubs/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:260)
    at __nccwpck_require__ (/Users/blkboxng/Desktop/publicTradesProperties/snaphubs/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

The error says to run `npx browserslist@latest --update-db` , and after running that I got another error:

```
npx browserslist@latest --update-db                                                                          1 ↵ blkboxng@Chris
New version: 1.0.30001366
Removing old caniuse-lite from lock file
Installing new caniuse-lite version
$ npm install caniuse-lite
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @reach/portal@0.11.2
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@">=14" from @builder.io/react@1.1.47
npm ERR!   node_modules/@builder.io/react
npm ERR!     peer @builder.io/react@"^1.1.0" from @builder.io/widgets@1.2.19
npm ERR!     node_modules/@builder.io/widgets
npm ERR!       @builder.io/widgets@"^1.2.19" from the root project
npm ERR!     @builder.io/react@"^1.1.47" from the root project
npm ERR!   react@">=14" from @builder.io/widgets@1.2.19
npm ERR!   node_modules/@builder.io/widgets
npm ERR!     @builder.io/widgets@"^1.2.19" from the root project
npm ERR!   48 more (@next/react-dev-overlay, next, @emotion/core, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from @reach/portal@0.11.2
npm ERR! node_modules/@reach/portal
npm ERR!   @reach/portal@"^0.11.2" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^16.8.0" from @reach/portal@0.11.2
npm ERR!   node_modules/@reach/portal
npm ERR!     @reach/portal@"^0.11.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/blkboxng/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/blkboxng/.npm/_logs/2022-07-13T17_21_52_408Z-debug-0.log
Error: Command failed: npm install caniuse-lite
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @reach/portal@0.11.2
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@">=14" from @builder.io/react@1.1.47
npm ERR!   node_modules/@builder.io/react
npm ERR!     peer @builder.io/react@"^1.1.0" from @builder.io/widgets@1.2.19
npm ERR!     node_modules/@builder.io/widgets
npm ERR!       @builder.io/widgets@"^1.2.19" from the root project
npm ERR!     @builder.io/react@"^1.1.47" from the root project
npm ERR!   react@">=14" from @builder.io/widgets@1.2.19
npm ERR!   node_modules/@builder.io/widgets
npm ERR!     @builder.io/widgets@"^1.2.19" from the root project
npm ERR!   48 more (@next/react-dev-overlay, next, @emotion/core, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from @reach/portal@0.11.2
npm ERR! node_modules/@reach/portal
npm ERR!   @reach/portal@"^0.11.2" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^16.8.0" from @reach/portal@0.11.2
npm ERR!   node_modules/@reach/portal
npm ERR!     @reach/portal@"^0.11.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/blkboxng/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/blkboxng/.npm/_logs/2022-07-13T17_21_52_408Z-debug-0.log

    at checkExecSyncError (node:child_process:820:11)
    at Object.execSync (node:child_process:891:15)
    at updateDB (/Users/blkboxng/Desktop/publicTradesProperties/snaphubs/node_modules/browserslist/update-db.js:146:18)
    at Object.<anonymous> (/Users/blkboxng/Desktop/publicTradesProperties/snaphubs/node_modules/browserslist/cli.js:40:3)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
Problem with `npm install` call. Run it manually.
```
Can someone help resolve this?

Thanks in advance

**Comment by ancheetah** [comment]
Hey @ChrisB007! I'm looking into this and trying to reproduce. Were there any changes you made to the dependencies after you cloned the starter? Can you also share which versions of node.js and npm you are using?

**Comment by ancheetah** [comment]
@ChrisB007 I got the same error using node v18.4. For now try using node v12-15 and lmk if you're still running into the issue. Thanks!

**Comment by ChrisB007** [comment]
Thanks, downgrading node version resolved the issue .. Thanks!!
