### ISSUE TITLE
Package subpath './lib/parser' is not defined by "exports (poscss)

### ISSUE THREAD

**Issue by jeanfrancoislarente** [BuilderIO/nextjs-shopify#42]
Running node 18.12.1 (npm 8.19.2)

Getting the following error when running `npm run dev`

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/parser' is not defined by "exports" in C:\projects\sitecore-ladybug\node_modules\postcss\package.json
    at new NodeError (node:internal/errors:393:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:358:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:668:3)
    at resolveExports (node:internal/modules/cjs/loader:529:36)
    at Module._findPath (node:internal/modules/cjs/loader:569:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at mod._resolveFilename (C:\projects\sitecore-ladybug\node_modules\next\dist\build\webpack\require-hook.js:4:1784)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at 552 (C:\projects\sitecore-ladybug\node_modules\next\dist\compiled\postcss-scss\scss-syntax.js:1:11590)
    at __nccwpck_require__ (C:\projects\sitecore-ladybug\node_modules\next\dist\compiled\postcss-scss\scss-syntax.js:1:11735)
    at 270 (C:\projects\sitecore-ladybug\node_modules\next\dist\compiled\postcss-scss\scss-syntax.js:1:400)
    at __nccwpck_require__ (C:\projects\sitecore-ladybug\node_modules\next\dist\compiled\postcss-scss\scss-syntax.js:1:11735)
    at 327 (C:\projects\sitecore-ladybug\node_modules\next\dist\compiled\postcss-scss\scss-syntax.js:1:260)
    at __nccwpck_require__ (C:\projects\sitecore-ladybug\node_modules\next\dist\compiled\postcss-scss\scss-syntax.js:1:11735) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by teleaziz** [comment]
Please use node engine that's less than 18, I updated package.json to warn you if you're not using the right version  "node" : ">=8.0.0 <16.0.0"

**Comment by teleaziz** [comment]
Starter was updated with latest packages, mainly next 13 and react 18
