### ISSUE TITLE
404 page not found on landing page

### ISSUE THREAD

**Issue by AlphaRaw** [BuilderIO/nextjs-shopify#45]

**Comment by AlphaRaw** [comment]
Providing a screenshot, I tried to fiddle with the operations.tsx but couldn't get anything working. If someone could help or point me in the right direction I'd greatly appreciate it.

**Comment by AlphaRaw** [comment]
![Screenshot_3](https://github.com/BuilderIO/nextjs-shopify/assets/69127859/961e3129-a0e2-4828-83ba-9b51b1569a92)

**Comment by AlphaRaw** [comment]
`error - TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11522:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getAllProductPaths (webpack-internal:///./lib/shopify/storefront-data-hooks/src/api/operations.ts:22:26)
    at async getStaticPaths (webpack-internal:///./pages/product/[handle].tsx:57:19)
    at async Object.buildStaticPaths (/home/ajrod/react-projects/nextjs-shopify/node_modules/next/dist/build/utils.js:598:33) {
  type: 'TypeError',
  cause: {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'https'
  },
  page: '/product/[handle]'
}`
